//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_Items
    {
        public string Items { get; set; }
        public string Remark { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Total { get; set; }
        public System.Guid Puid { get; set; }
        public System.Guid Uid { get; set; }
        public string cruser { get; set; }
        public Nullable<System.DateTime> crdate { get; set; }
        public string eduser { get; set; }
        public Nullable<System.DateTime> eddate { get; set; }
        public string sctrl { get; set; }
    }
}
