//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MISEntities : DbContext
    {
        public MISEntities()
            : base("name=MISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budget_Bugda> Budget_Bugda { get; set; }
        public virtual DbSet<Comm_Account> Comm_Account { get; set; }
        public virtual DbSet<Dept> Dept { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Tuser> Tuser { get; set; }
        public virtual DbSet<Bugda> Bugda { get; set; }
        public virtual DbSet<Budget_Items> Budget_Items { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Budget_t> Budget_t { get; set; }
        public virtual DbSet<Lev_Step> Lev_Step { get; set; }
    
        public virtual int Step_Insert(string bno, string system, string type, string cruser)
        {
            var bnoParameter = bno != null ?
                new ObjectParameter("Bno", bno) :
                new ObjectParameter("Bno", typeof(string));
    
            var systemParameter = system != null ?
                new ObjectParameter("system", system) :
                new ObjectParameter("system", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var cruserParameter = cruser != null ?
                new ObjectParameter("cruser", cruser) :
                new ObjectParameter("cruser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Step_Insert", bnoParameter, systemParameter, typeParameter, cruserParameter);
        }
    
        public virtual int UpdateTotal(string puid)
        {
            var puidParameter = puid != null ?
                new ObjectParameter("Puid", puid) :
                new ObjectParameter("Puid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTotal", puidParameter);
        }
    
        public virtual ObjectResult<Budget_Step> Bugda_select(string penno)
        {
            var pennoParameter = penno != null ?
                new ObjectParameter("Penno", penno) :
                new ObjectParameter("Penno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Budget_Step>("Bugda_select", pennoParameter);
        }
    
        public virtual int Step_Signoff(string penno, string bno)
        {
            var pennoParameter = penno != null ?
                new ObjectParameter("Penno", penno) :
                new ObjectParameter("Penno", typeof(string));
    
            var bnoParameter = bno != null ?
                new ObjectParameter("Bno", bno) :
                new ObjectParameter("Bno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Step_Signoff", pennoParameter, bnoParameter);
        }
    }
}
